spring:
  application:
    name: flutter_api_java

  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/wave_database
    username: postgres
    password: ehacsish
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
